// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

#if PLATFORM_KAKAO
namespace Kakaogame.SDK.Editor {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class Permissions : PermissionsBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            this.Write("\n<!-- KakaoGameSDK Permission(Common) Start -->\n<uses-permission android:name=\"android.permission.INTERNET\" />\n<uses-permission android:name=\"android.permission.ACCESS_NETWORK_STATE\" />\n<uses-permission android:name=\"com.android.launcher.permission.INSTALL_SHORTCUT\" />\n<!-- KakaoGameSDK Permission(Common) End -->\n\n");
            
            
 if(platforms.Contains("push")) { 
            
            
            this.Write("<!-- KakaoGameSDK Permission(Push) Start -->\n<uses-permission android:name=\"android.permission.USE_CREDENTIALS\" />\n<uses-permission android:name=\"android.permission.WAKE_LOCK\" />\n<uses-permission android:name=\"android.permission.VIBRATE\" />\n<uses-permission android:name=\"com.google.android.c2dm.permission.RECEIVE\" />\n<permission\n\tandroid:name=\"");
            
            
            this.Write(this.ToStringHelper.ToStringWithCulture( packageName ));
            
            
            this.Write(".permission.C2D_MESSAGE\"\n\tandroid:protectionLevel=\"signature\" />\n<uses-permission android:name=\"");
            
            
            this.Write(this.ToStringHelper.ToStringWithCulture( packageName ));
            
            
            this.Write(".permission.C2D_MESSAGE\" />\n<!-- KakaoGameSDK Permission(Push) End -->\n");
            
            
 } 
            
            
            this.Write("\n");
            
            
 if(platforms.Contains("google")) { 
            
            
            this.Write("<!-- KakaoGameSDK Permission(Google) Start -->\n<uses-permission android:name=\"android.permission.USE_CREDENTIALS\" />\n<!-- KakaoGameSDK Permission(Google) End -->\n");
            
            
 } 
            
            
            this.Write("\n");
            
            
 if(platforms.Contains("kakao")) { 
            
            
            this.Write("<!-- KakaoGameSDK Permission(Kakao) Start -->\n<uses-permission android:name=\"android.permission.WRITE_EXTERNAL_STORAGE\" />\n<uses-permission android:name=\"android.permission.READ_EXTERNAL_STORAGE\" />\n<!-- KakaoGameSDK Permission(Kakao) End -->\n");
            
            
 } 
            
            
            this.Write("\n");
            
            
 if(platforms.Contains("reachkakao")) { 
            
            
            this.Write("<!-- KakaoGameSDK Permission(Reachkakao) Start -->\n<uses-permission android:name=\"android.permission.RECEIVE_SMS\" />\n<uses-feature android:name=\"android.hardware.telephony\" android:required=\"false\"/>\n<!-- KakaoGameSDK Permission(Reachkakao) End -->\n\n<!-- KakaoGameSDK Permission(Custom) Start -->\n");
            
            
 foreach(var permission in permissions) { 
            
            
            this.Write("<uses-permission android:name=\"android.permission.");
            
            
            this.Write(this.ToStringHelper.ToStringWithCulture( permission ));
            
            
            this.Write("\" />\n");
            
            
 } 
            
            
            this.Write("<!-- KakaoGameSDK Permission(Custom) End -->\n\n");
            
            
 } 
            
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class PermissionsBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError());
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError();
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
#endif
